### ISSUE TITLE
can't find  lib

### ISSUE THREAD

**Issue by bestpredicts** [aijunbai/rcg_player#1]
./bin/rcg_player: error while loading shared libraries: libboost_program_options.so.1.58.0: cannot open shared object file: No such file or directory
and  I do this:
d@d:~/boost_1_46_1/stage/lib$ sudo  ln  -s  libboost_program_options.so  /usr/lib/
but no use 
how can i slove it?

**Comment by aijunbai** [comment]
Hi, please try to run ./build.sh first to compile it on your own machine.

**Comment by aijunbai** [comment]
You should also install the dependencies:
libqt4-dev
qt4-qmake
libboost-all-dev
